# Generated by Django 3.2 on 2022-10-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
    ]
