# Generated by Django 3.2 on 2022-11-16 04:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
