# Generated by Django 4.1.2 on 2022-10-17 15:53

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userprofile_alter_user_id_delete_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(max_length=30, verbose_name=userapp.models.user),
        ),
    ]
